### ISSUE TITLE
Missing /src directory in your repo

### ISSUE THREAD

**Issue by yzhwang** [Beatgodes/BoruvkaUMinho#1]
Hi Cristiano,

I want to try your code (btw, very nice paper!). However, I find that you seem to miss the src directory. The GPU and OMP implementation are all there. Could you add that so that I can play with the code? We have a GPU graph library which has a MST implementation too, and we really want to learn how you make Boruvka faster. Thank you a lot!

**Comment by Beatgodes** [comment]
Code has been added.
